# x=input("Enter your age")
# print(x)
# print(type(x))

# x= int(input("Enter your age"))
# print(x)
# print(type(x))
collection=(11,23,44,56,6,6)
print(ord("A"))
print(chr(65))
print(float(5))
print(complex(5))
print(list(collection))